apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:    #replica set labels
    app: frontend
    tier: web
    project: expense 
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:  #these are used to select the pod to create replicas
      app: frontend
      tier: web
      project: expense
  template:   #this is pod template
    metadata:
      labels:  #these labels belongs to pod 
        app: frontend
        tier: web
        project: expense 
    spec:
      containers:
      - name: frontend
        image: santhan29/frontend:v1 
---
kind: Service
apiVersion: v1
metadata:
 name: frontend
 namespace: expense1 
spec: 
  type: LoadBalancer 
  selector:
    app: frontend
    tier: web
    project: expense 
  ports:
    - name: frontend-port
      protocol: TCP
      port: 80  #service port
      targetPort: 80 #container port 